apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-fe-deployment
#  namespace: hindalco
  labels:
    app: local-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-fe
  template:
    metadata:
      labels:
        app: local-fe
    spec:
      containers:
      - name: local-fe
        image: hcorptech/hindalco-local
        ports:
        - containerPort: 80
       # envFrom:
       # - configMapRef:
        #   name: common-config
---
apiVersion: v1
kind: Service
metadata:
  name: local-fe
  #namespace: hindalco
spec:
  selector:
    app: local-fe
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    #nodePort: 30081 
