export const BaseUrl = 'http://192.168.1.50:9090/auth/'
export const BaseUrl1 = 'http://192.168.1.50:8081/api/'
export const LoginApi = BaseUrl+'login'
export const ReaderDataApi = BaseUrl+'reader'
export const addRole = BaseUrl1+'addRole'
export const getRoles = BaseUrl+'getRoles'
export const addSite = BaseUrl+'addSite'