apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: NodePort  # Use ClusterIP if you don't need an external load balancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: react-app

