export const SET_AUTH = 'SET_AUTH'
export const SET_ROAD_DATA = 'SET_ROAD_DATA'
export const SET_ROAD_JSON = 'SET_ROAD_JSON'

export const SET_COMPLETE_COMPACTOIN_DATA = 'SET_COMPLETE_COMPACTOIN_DATA'

export const SET_EMPLOYEE_DATA = 'SET_EMPLOYEE_DATA'
export const SET_EMPLOYEE_JSON = 'SET_EMPLOYEE_JSON'

